// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bewgwsfjdmdqsxezralk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJld2d3c2ZqZG1kcXN4ZXpyYWxrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM0MzIyNTMsImV4cCI6MjA1OTAwODI1M30.MzWftUGBSF_9XNT-xqp_gN24jnpdN7_B3r8nhXv6z4U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);